name: Create release and asset

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  release:
    types: 
      - published
env:
  # Pretty cargo output!
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build | install dependencies
      run: |
          sudo apt-get -qq update
          sudo apt install -qq -y protobuf-compiler
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
          sudo apt install zip
    - name: Build
      run: cargo build --release --verbose
    - name: Create Distribution Folder
      run: mkdir distributions
    - name: Copy files
      run: |
          cp .env distributions/
          cp target/release/server distributions/
          
    - name: Compress Files
      run: zip -r adempiere-backend-rs.zip distributions/
    - name: Upload Binary Files
      uses: actions/upload-artifact@v3
      with:
          name: adempiere-backend-rs
          path: distributions/
    - name: Upload Binary
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'adempiere-backend-rs.zip'
    # Check secrets to push image in docker hub registry
  check-docker-secrets:
    name: Check if docker hub registry information was set on secrets
    needs:
      - build-app
    runs-on: ubuntu-latest
    outputs:
      is_have_secrets: ${{ steps.check_secret_job.outputs.is_have_secrets }}
    steps:
      - id: check_secret_job
        run: |
          if [[ "${{ secrets.DOCKER_REPO_ADEMPIERE_BACKEND }}" != "" && \
                "${{ secrets.DOCKER_USERNAME }}" != "" && \
                "${{ secrets.DOCKER_TOKEN }}" != "" ]]; \
          then
            echo "Secrets to use a container registry are configured in the repo"
            echo "is_have_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "Secrets to use a container registry were not configured in the repo"
            echo "is_have_secrets=false" >> $GITHUB_OUTPUT
          fi


  # TODO: Download .tar and add docker image without uncompress
  # Publish docker alpine image in Docker Hub Registry to application
  push-imame-dhr:
    name: Push docker alpine image to Docker Hub
    needs:
      - check-docker-secrets
    # Skip step based on secret
    if: needs.check-docker-secrets.outputs.is_have_secrets == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Download build dist app
        uses: actions/download-artifact@v3
        with:
          name: adempiere-middleware.zip
          path: dist

      - name: Unzip dist file
        run: |
          cd dist
          unzip -o adempiere-middleware.zip

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          # CONFIGURE DOCKER SECRETS INTO REPOSITORY
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push alpine image in Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REPO_ADEMPIERE_BACKEND }}:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKER_REPO_ADEMPIERE_BACKEND }}
